# Generated by Django 3.1.2 on 2020-10-31 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_degree', models.SmallIntegerField()),
                ('authorit_query', models.BooleanField()),
                ('authorit_add', models.BooleanField()),
                ('authorit_delete', models.BooleanField()),
                ('authorit_update', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='normal_user',
            name='user_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normal_user.authority'),
        ),
    ]
